version: '3.3'

services:
  db:
    container_name: 'db'
    build:
      context: .
      dockerfile: ./db/Dockerfile.postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      TZ: Europe/Moscow
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - rent-network
networks:
  rent-network:
    driver: bridge
